events
{
    worker_connections 42;
}

http 
{
    ssl_protocols        TLSv1.2 TLSv1.3;

    ssl_certificate      /etc/nginx/ssl/inception.crt;
    ssl_certificate_key  /etc/nginx/ssl/inception.key;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen       443 ssl;
        server_name  eprieur.42.fr;

        client_max_body_size 1000000;
        root /var/www/wordpress;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
            include fastcgi_params;
        }
    }
    server {
        listen       443 ssl;
        server_name  static.eprieur.42.fr;

        location / {
            proxy_pass http://static_web_site:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
    server {
        listen       443 ssl;
        server_name  admin.eprieur.42.fr;

        location / {
            proxy_pass http://adminer:8080;
        }
    }
    server {
        listen       443 ssl;
        server_name  portainer.eprieur.42.fr;

        location / {
            proxy_pass http://portainer:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
