services:
  adminer:
    container_name: adminer_container
    env_file: .env
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    image: adminer
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - inception_network

  static_web_site:
    container_name: static_web_container
    env_file: .env
    build:
      context: ./requirements/nginx/website
      dockerfile: Dockerfile
    image: nginx-static-site
    restart: on-failure
    networks:
      - inception_network

  redis:
    container_name: redis_container
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    image: redis
    restart: on-failure
    networks:
      - inception_network