services:
  mariadb:
    container_name: server_mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: on-failure
    entrypoint: /usr/local/bin/init.sh
    volumes: 
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception_network
  worldpress:
    container_name: server_worldpress
    build:
      context: ./requirements/worldpress
      dockerfile: Dockerfile
    image: worldpress
    restart: on-failure
    entrypoint: /usr/local/bin/init.sh
    volumes:
      - worldpress_data:/var/www/worldpress
    secrets:
      - wp_admin_password
      - wp_password
    networks:
      - inception_network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eprieur/data/mariadb
  worldpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eprieur/data/worldpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
networks:
  inception_network:
    driver: bridge