services:
  mariadb:
    container_name: mariadb_container
    env_file: .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: on-failure
    volumes: 
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception_network

  wordpress:
    container_name: wordpress_container
    env_file: .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_password
    networks:
      - inception_network

  nginx:
    container_name: nginx_container
    env_file: .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: on-failure
    ports:
    - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
    - inception_network
  
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eprieur/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eprieur/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
networks:
  inception_network:
    driver: bridge