#listen
listen=YES
listen_ipv6=NO

anonymous_enable=NO

#user-perm-time
use_localtime=YES
local_enable=YES
local_umask=022
write_enable=YES

#dir
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd

#log
xferlog_enable=YES
xferlog_std_format=YES

tcp_wrappers=YES
ssl_enable=NO

#listen
pasv_enable=YES
pasv_min_port=42000
pasv_max_port=42010
port_enable=YES